KS-1-5-DZ seconds in space
TaniQAs/KotlinSprint pull request #8
Opened 2024-08-20 09:45 UTC by TaniQAs

2024-08-20 19:12 UTC, ievetrovdev requested changes

2024-08-20 19:12 UTC, ievetrovdev commented on src/main/kotlin/lesson_1_DZ/lesson_1_5.kt
> +    val minutes = seconds / 60
Чтобы снизить риск ошибок, предлагаю все “голые” числа вынести в константу. Кроме того это [магические числа](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F), что тоже не является хорошей практикой.

2024-08-20 19:12 UTC, ievetrovdev commented on src/main/kotlin/lesson_1_DZ/lesson_1_5.kt
> +    println("0" + hours + ":" + remainderMinutes + ":00")
Так как это 5 задача ("со звездочкой") не по уровню урока, то предлагаю использовать более элегантное решение). (может потребовать дополнительного ресерча). Для корректного вывода нуля вначале попробуй посмотреть в сторону String.format().

2024-08-23 07:49 UTC, TaniQAs commented on src/main/kotlin/lesson_1_DZ/lesson_1_5.kt
> +    val minutes = seconds / 60
Исправила

2024-08-23 07:49 UTC, TaniQAs commented on src/main/kotlin/lesson_1_DZ/lesson_1_5.kt
> +    println("0" + hours + ":" + remainderMinutes + ":00")
Исправила

2024-08-23 14:52 UTC, ievetrovdev approved these changes

2024-08-23 14:52 UTC, ievetrovdev commented on src/main/kotlin/lesson_1_DZ/lesson_1_5.kt
> +const val MINUTES_IN_HOUR = 60
Все хорошо, тут достаточно одной константы, например SECONDS_IN_MINUTE

2024-08-23 14:52 UTC, ievetrovdev commented on src/main/kotlin/lesson_1_DZ/lesson_1_5.kt
> +    //  println(minutes)
На будущее - комментированный код лучше не оставлять, если на это нет действительно веских причин.

2024-08-23 16:47 UTC, TaniQAs commented on src/main/kotlin/lesson_1_DZ/lesson_1_5.kt
> +    //  println(minutes)
Спасибо за ценные комментарии!

2024-08-23 16:49 UTC, merged