KS-2-1-DZ average mark
TaniQAs/KotlinSprint pull request #9
Opened 2024-08-20 16:54 UTC by TaniQAs

2024-08-21 07:39 UTC, ievetrovdev requested changes

2024-08-21 07:39 UTC, ievetrovdev commented on src/main/kotlin/lesson_2_DZ/lesson_2_1.kt
> +    val a: Float = 3f
Однобуквенные переменные - зло, они уместны только в циклах в качестве интерируемой переменной, в остальном - теряется контекст в месте использования переменной. Давай дадим понятное название
дробные переменные можно писать с точкой 3.0

2024-08-21 07:49 UTC, TaniQAs commented on src/main/kotlin/lesson_2_DZ/lesson_2_1.kt
> +    val a: Float = 3f
Понятно, спасибо за комментарий.

2024-08-21 07:53 UTC, TaniQAs commented on src/main/kotlin/lesson_2_DZ/lesson_2_1.kt
> +    val a: Float = 3f
Исправила

2024-08-21 13:53 UTC, ievetrovdev approved these changes

2024-08-21 13:53 UTC, ievetrovdev requested changes

2024-08-21 13:53 UTC, ievetrovdev commented on src/main/kotlin/lesson_2_DZ/lesson_2_1.kt
> +    val markPerson1: Float = 3.0f
используя точку f можно опустить

2024-08-21 14:13 UTC, TaniQAs commented on src/main/kotlin/lesson_2_DZ/lesson_2_1.kt
> +    val a: Float = 3f
Я как-то убрала твой комментарий про f)

Если я убираю f, то получаю ошибку:
The floating-point literal does not conform to the expected type Float

2024-08-23 14:08 UTC, ievetrovdev approved these changes

2024-08-23 17:10 UTC, merged